{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "To-do's API",
    "description": "A simple To-Dos App"
  },
  "host": "todos.stoplight.io",
  "schemes": ["http"],
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "securityDefinitions": { "apikey": { "name": "apikey", "type": "apiKey", "in": "query" } },
  "paths": {
    "/todos/{todoId}": {
      "parameters": [{ "name": "todoId", "in": "path", "required": true, "type": "string" }],
      "get": {
        "operationId": "GET_todo",
        "summary": "Get Todo",
        "tags": ["Todos"],
        "responses": {
          "200": {
            "description": "",
            "schema": { "$ref": "#/definitions/todo-full" },
            "examples": {
              "application/json": {
                "name": "",
                "completed": false,
                "id": -11923219,
                "completed_at": "1955-04-23T13:22:52.685Z",
                "created_at": "1994-11-05T03:26:51.471Z",
                "updated_at": "1989-07-29T11:30:06.701Z"
              }
            }
          },
          "401": { "$ref": "#/responses/trait:standardErrors:401" },
          "404": { "$ref": "#/responses/trait:standardErrors:404" }
        }
      },
      "put": {
        "operationId": "PUT_todos",
        "summary": "Update Todo",
        "tags": ["Todos"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/todo-partial",
              "example": { "name": "my todo's new name", "completed": false }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": { "$ref": "#/definitions/todo-full" },
            "examples": {
              "application/json": {
                "id": 9000,
                "name": "It's Over 9000!!!",
                "completed": true,
                "completed_at": null,
                "created_at": "2014-08-28T14:14:28.494Z",
                "updated_at": "2015-08-28T14:14:28.494Z"
              }
            }
          },
          "401": { "$ref": "#/responses/trait:standardErrors:401" },
          "403": { "description": "", "schema": { "type": "object" } },
          "404": { "$ref": "#/responses/trait:standardErrors:404" }
        },
        "security": [{ "apikey": [] }]
      },
      "delete": {
        "operationId": "DELETE_todo",
        "summary": "Delete Todo",
        "tags": ["Todos"],
        "responses": {
          "204": { "description": "" },
          "401": { "$ref": "#/responses/trait:standardErrors:401" },
          "404": { "$ref": "#/responses/trait:standardErrors:404" }
        },
        "security": [{ "apikey": [] }]
      }
    },
    "/todos": {
      "post": {
        "operationId": "POST_todos",
        "summary": "Create Todo",
        "tags": ["Todos"],
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/todo-partial",
              "example": { "name": "My todo's name", "completed": false }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "",
            "schema": { "$ref": "#/definitions/todo-full" },
            "examples": {
              "application/json": {
                "id": 9000,
                "name": "It's Over 9000!!!",
                "completed": null,
                "completed_at": null,
                "created_at": "2014-08-28T14:14:28.494Z",
                "updated_at": "2014-08-28T14:14:28.494Z"
              }
            }
          },
          "401": { "$ref": "#/responses/trait:standardErrors:401" },
          "403": { "description": "", "schema": { "type": "object", "properties": {} } },
          "404": { "$ref": "#/responses/trait:standardErrors:404" }
        },
        "security": [{ "apikey": [] }]
      },
      "get": {
        "operationId": "GET_todos",
        "summary": "List Todos",
        "tags": ["Todos"],
        "parameters": [
          { "$ref": "#/parameters/trait:paged:limit" },
          { "$ref": "#/parameters/trait:paged:skip" }
        ],
        "responses": {
          "200": {
            "description": "",
            "schema": { "type": "array", "items": { "$ref": "#/definitions/todo-full" } },
            "examples": {
              "application/json": [
                {
                  "name": "e",
                  "completed": true,
                  "id": -98347857,
                  "completed_at": "1994-08-18T08:51:43.848Z",
                  "created_at": "1970-01-16T22:43:08.119Z",
                  "updated_at": "1990-03-15T23:10:32.764Z"
                },
                {
                  "name": "c",
                  "completed": null,
                  "id": -93973177,
                  "completed_at": null,
                  "created_at": "1951-07-27T02:03:31.565Z",
                  "updated_at": "1955-08-01T19:01:06.474Z"
                },
                {
                  "name": "e",
                  "completed": null,
                  "id": -39249051,
                  "completed_at": "1980-04-23T18:48:15.392Z",
                  "created_at": "1987-11-25T14:03:32.541Z",
                  "updated_at": "1961-07-19T16:52:20.267Z"
                }
              ]
            }
          },
          "300": {
            "description": "",
            "schema": {
              "type": "object",
              "properties": {
                "WriteTime": { "type": "string", "format": "date" },
                "Status": { "type": "string" }
              }
            },
            "examples": { "application/json": {} }
          },
          "401": { "$ref": "#/responses/trait:standardErrors:401" },
          "404": {
            "$ref": "#/responses/trait:standardErrors:404",
            "examples": { "application/json": { "error": "not found" } }
          },
          "500": {
            "description": "",
            "schema": { "type": "object", "properties": { "message": { "type": "string" } } },
            "examples": {
              "application/json": { "message": "default" }
            }
          }
        }
      }
    }
  },
  "parameters": {
    "trait:paged:limit": {
      "name": "limit",
      "in": "query",
      "description": "This is how it works.",
      "required": false,
      "type": "integer",
      "maximum": 100
    },
    "trait:paged:skip": { "name": "skip", "in": "query", "required": false, "type": "string" }
  },
  "responses": {
    "trait:standardErrors:401": { "description": "", "schema": { "type": "object" } },
    "trait:standardErrors:404": {
      "description": "",
      "schema": {
        "type": "object",
        "properties": { "status": { "type": "string" }, "error": { "type": "string" } },
        "required": ["status", "error"]
      },
      "examples": { "application/json": { "error": "not found", "status": "err" } }
    },
    "trait:standardErrors:403": {
      "description": "",
      "schema": {
        "type": "object",
        "properties": { "message": { "type": "string" } },
        "required": ["message"]
      }
    },
    "trait:standardErrors:500": { "description": "", "schema": { "type": "object" } }
  },
  "definitions": {
    "todo-partial": {
      "title": "Todo Partial",
      "type": "object",
      "properties": { "name": { "type": "string" }, "completed": { "type": ["boolean", "null"] } },
      "required": ["name"]
    },
    "todo-full": {
      "title": "Todo Full",
      "allOf": [
        { "$ref": "#/definitions/todo-partial" },
        {
          "type": "object",
          "properties": {
            "id": { "type": "integer", "maximum": 1 },
            "completed_at": { "type": ["string", "null"], "format": "date-time" },
            "created_at": { "type": "string", "format": "date-time" },
            "updated_at": { "type": "string", "format": "date-time" }
          },
          "required": ["id"]
        }
      ]
    }
  }
}